# Generated by Django 4.1.4 on 2023-02-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Neck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.BigIntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.category')),
                ('fit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.fit')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.material')),
                ('neck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.neck')),
                ('pattern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.pattern')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sleeve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeve_type', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('sku', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.products')),
                ('size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.size')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='sleeve_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sleeve'),
        ),
    ]
