# Generated by Django 4.1.4 on 2023-02-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_seller_status'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.seller'),
        ),
    ]
