# Generated by Django 4.1.4 on 2023-02-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_products_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='sku',
        ),
    ]
