# Generated by Django 4.1.4 on 2023-03-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_rename_image_products_thumbnail_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size_guide',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
