# Generated by Django 4.1.4 on 2023-03-22 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_products_size_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='fit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.fit'),
        ),
        migrations.AlterField(
            model_name='products',
            name='neck_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.neck'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size_guide',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sleeve_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.sleeve'),
        ),
    ]
