# Generated by Django 4.1.4 on 2023-03-25 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_products_fit_id_alter_products_neck_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pattern_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.pattern'),
        ),
    ]
