# Generated by Django 4.1.4 on 2023-02-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('account', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('ifsc', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('sellerpic', models.ImageField(upload_to='seller/')),
            ],
        ),
    ]
