# Generated by Django 4.1.4 on 2023-02-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
