# Generated by Django 4.1.4 on 2023-03-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
